theme: jekyll-theme-minimal
title: Gabriella Pizzuto
description: I am Gabriella Pizzuto, a graduate engineer specialised in robotics, machine learning and control theory. 
I have gained an interdisciplinary background from experience in both academia and industry. Throughout my research career, I have obtained skills in deep learning,
machine learning, developmental robotics, cognitive robotics, computational neuroscience, computational motor control, control theory, electronics and biomedical engineering. 
I have completed a postgraduate Master’s degree in cognitive robotics and computational neuroscience at the University
of Birmingham. Currently I am employed as a Marie Curie early stage researcher whilst pursuing a PhD in cognitive robotics at the University of Plymouth (transferring to the University of Manchester
in 2018).
