title: Gabriella Pizzuto
description: Early Stage Researcher in Cognitive Robotics at University of Plymouth.
show_downloads: false
google_analytics:
email_address: gabriella.pizzuto@plymouth.ac.uk

show_excerpts: true
theme: jekyll-theme

plugins:
  - jemoji
  - jekyll-email-protect
